name: Docker Build

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t sakmalh/fe-diffusion .

    - name: Login to Docker Hub
      env:
        DOCKERPASS: ${{ secrets.DOCKERPASS }}
      run: echo $DOCKERPASS | docker login -u sakmalh --password-stdin

    - name: Push Docker image
      run: docker push sakmalh/fe-diffusion